// web/src/routes/characters/[slug]/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import {
		getFullName, getNationalityFlag, formatDate, formatRank,
		getHistoricalRankingAt, formatCitation, getCitationScore
	} from '$lib/utils';
	import { renderMd } from '$lib/markdown';

	let { data }: { data: PageData } = $props();
	const c    = $derived(data.character);
	const orbs = $derived(data.orbs);

	function getOrb(orbId: number) {
		return orbs.find(o => o.id === orbId) ?? null;
	}

	const latestRanking      = $derived(getHistoricalRankingAt(c.rankings));
	const firstKnownCitation = $derived(
		c.rankings.length
			? [...c.rankings].sort((a, b) => getCitationScore(a.citation) - getCitationScore(b.citation))[0].citation
			: null
	);

	// Most recent first — rankings use citation score as the sort key
	const sortedRankings = $derived(
		[...c.rankings].sort((a, b) => getCitationScore(b.citation) - getCitationScore(a.citation))
	);

	// Most recent first — stats use date then sequence
	const sortedStats = $derived(
		[...c.stats].sort((a, b) => {
			const da = a.date_noted ?? '', db = b.date_noted ?? '';
			if (db !== da) return db.localeCompare(da);
			return (b.date_sequence ?? 1) - (a.date_sequence ?? 1);
		})
	);
</script>

<svelte:head><title>{getFullName(c)} — D-Genesis Info</title></svelte:head>

<div class="container page">

	<a href={c.is_explorer ? '/explorers' : '/characters'} class="back-link">
		← {c.is_explorer ? 'Explorers' : 'Characters'}
	</a>

	<!-- ── Hero header ── -->
	<div class="char-hero__name-row">
		<h1 class="char-name">{getFullName(c)}</h1>
		{#if c.in_wdarl && !c.is_public}
			<span class="anon-badge">✦ Anonymous on WDARL</span>
		{/if}
	</div>
	{#if c.moniker}
		<p class="char-moniker">"{c.moniker}"</p>
	{/if}

	{#if c.tags?.length}
		<div class="char-tags">
			{#each c.tags as tag}<span class="tag">{tag}</span>{/each}
		</div>
	{/if}

	<!-- Metadata chips -->
	<div class="meta-chips">
		{#if c.is_explorer && latestRanking}
			<div class="meta-chip meta-chip--accent">
				<span class="meta-chip__label">Rank</span>
				<span class="meta-chip__value">{formatRank(latestRanking)}</span>
			</div>
		{/if}
		{#if c.sex}
			<div class="meta-chip">
				<span class="meta-chip__label">Sex</span>
				<span class="meta-chip__value">{c.sex === 'Male' ? '♂' : c.sex === 'Female' ? '♀' : c.sex}</span>
			</div>
		{/if}
		{#if c.nationality}
			<div class="meta-chip">
				<span class="meta-chip__label">Nationality</span>
				<span class="meta-chip__value">{getNationalityFlag(c.nationality)} {c.nationality}</span>
			</div>
		{/if}
		{#if c.area}
			<div class="meta-chip">
				<span class="meta-chip__label">Area</span>
				<span class="meta-chip__value">{c.area}</span>
			</div>
		{/if}
		{#if c.birthday}
			<div class="meta-chip">
				<span class="meta-chip__label">Birthday</span>
				<span class="meta-chip__value">🎂 {c.birthday}</span>
			</div>
		{/if}
		{#if c.date_first_known}
			<div class="meta-chip">
				<span class="meta-chip__label">First Known</span>
				<span class="meta-chip__value">{formatDate(c.date_first_known)}</span>
				{#if firstKnownCitation?.volume}
					<span class="badge badge--citation" style="margin-top: 0.2rem; align-self: flex-start;">{formatCitation(firstKnownCitation)}</span>
				{/if}
			</div>
		{/if}
	</div>

	<!-- ── Note ── -->
	{#if c.note}
		<div class="data-section">
			<p class="section-heading">Note</p>
			<div class="md-content note-content">
				{@html renderMd(c.note)}
			</div>
		</div>
	{/if}

	<!-- ── Rankings ── -->
	{#if c.is_explorer && sortedRankings.length}
		<div class="data-section">
			<details open>
				<summary class="section-heading collapsible">Rankings</summary>
				<div class="card" style="padding: 0; overflow: hidden; margin-top: 0.75rem;">
					<table class="data-table">
						<thead>
							<tr>
								<th>Rank</th>
								<th>Known Above</th>
								<th>Date Noted</th>
								<th>Citation</th>
							</tr>
						</thead>
						<tbody>
							{#each sortedRankings as r}
								<tr>
									<td class="rank-cell">{r.rank ? '#' + r.rank.toLocaleString() : '—'}</td>
									<td>{r.known_above_rank ? r.known_above_rank.toLocaleString() : '—'}</td>
									<td>{formatDate(r.date_noted)}</td>
									<td>
										{#if r.citation.volume}
											<span class="badge badge--citation">{formatCitation(r.citation)}</span>
										{:else}—{/if}
									</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			</details>
		</div>
	{/if}

	<!-- ── Stats ── -->
	{#if c.is_explorer && sortedStats.length}
		<div class="data-section">
			<details open>
				<summary class="section-heading collapsible">Stat Readings</summary>
				<div class="card" style="padding: 0; overflow: hidden; overflow-x: auto; margin-top: 0.75rem;">
					<table class="data-table stat-table">
						<thead>
							<tr>
								<th>Date</th>
								<th>Seq</th>
								<th>Type</th>
								<th>STR</th>
								<th>VIT</th>
								<th>INT</th>
								<th>AGI</th>
								<th>DEX</th>
								<th>LUC</th>
								<th>Total</th>
								<th>HP</th>
								<th>MP</th>
								<th>SP</th>
								<th>Citation</th>
							</tr>
						</thead>
						<tbody>
							{#each sortedStats as s}
								<tr>
									<td>{formatDate(s.date_noted)}</td>
									<td class="seq-cell">{s.date_sequence}</td>
									<td class="scan-type">{s.scan_type ?? '—'}</td>
									<td class="stat-val">{s.str ?? '—'}</td>
									<td class="stat-val">{s.vit ?? '—'}</td>
									<td class="stat-val">{s.int ?? '—'}</td>
									<td class="stat-val">{s.agi ?? '—'}</td>
									<td class="stat-val">{s.dex ?? '—'}</td>
									<td class="stat-val">{s.luc ?? '—'}</td>
									<td class="stat-total">{s.stat_total ?? '—'}</td>
									<td class="stat-val">{s.hp ?? '—'}</td>
									<td class="stat-val">{s.mp ?? '—'}</td>
									<td class="stat-val">{s.sp ?? '—'}</td>
									<td>
										{#if s.citation.volume}
											<span class="badge badge--citation">{formatCitation(s.citation)}</span>
										{:else}—{/if}
									</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			</details>
		</div>
	{/if}

	<!-- ── Orbs ── -->
	{#if c.is_explorer && c.orbs_used.length}
		<div class="data-section">
			<details open>
				<summary class="section-heading collapsible">Skill Orbs</summary>
				<div class="card" style="padding: 0; overflow: hidden; margin-top: 0.75rem;">
					<table class="data-table">
						<thead>
							<tr>
								<th>Orb</th>
								<th>Date Acquired</th>
								<th>Citation</th>
							</tr>
						</thead>
						<tbody>
							{#each c.orbs_used as ou}
								{@const orb = getOrb(ou.orb_id)}
								<tr>
									<td>
										{#if orb}
											<a href="/orbs/{orb.slug}">{orb.orb_name}</a>
										{:else}Unknown{/if}
									</td>
									<td>{ou.date_acquired ? formatDate(ou.date_acquired) : (ou.date_note ?? '—')}</td>
									<td>
										{#if ou.citation.volume}
											<span class="badge badge--citation">{formatCitation(ou.citation)}</span>
										{:else}—{/if}
									</td>
								</tr>
							{/each}
						</tbody>
					</table>
				</div>
			</details>
		</div>
	{/if}

</div>

<style>
	/* ── Hero ── */
	.char-hero__name-row {
		display: flex;
		align-items: center;
		gap: 0.75rem;
		flex-wrap: wrap;
		margin-bottom: 0.25rem;
	}

	.char-name {
		font-size: 2.5rem;
		font-weight: 800;
		letter-spacing: -0.03em;
		line-height: 1.1;
	}

	.anon-badge {
		font-size: 0.6875rem;
		font-weight: 700;
		letter-spacing: 0.06em;
		text-transform: uppercase;
		padding: 0.3em 0.75em;
		border-radius: 999px;
		background: #fee2e2;
		color: #b91c1c;
		border: 1px solid #fca5a5;
		white-space: nowrap;
	}

	.char-moniker {
		font-size: 1.0625rem;
		color: var(--text-3);
		font-style: italic;
		margin-bottom: 0.5rem;
	}

	/* ── Tags (near name) ── */
	.char-tags {
		display: flex;
		flex-wrap: wrap;
		gap: 0.375rem;
		margin-bottom: 1rem;
	}

	.tag {
		font-size: 0.75rem;
		padding: 0.2em 0.6em;
		background: var(--bg-subtle);
		border: 1px solid var(--border);
		border-radius: 999px;
		color: var(--text-3);
	}

	/* ── Metadata chips ── */
	.meta-chips {
		display: flex;
		flex-wrap: wrap;
		gap: 0.5rem;
		margin-bottom: 1rem;
	}

	.meta-chip {
		display: flex;
		flex-direction: column;
		gap: 0.2rem;
		padding: 0.4rem 0.75rem;
		background: var(--bg-subtle);
		border: 1px solid var(--border);
		border-radius: var(--radius);
	}

	.meta-chip--accent {
		background: var(--accent-bg);
		border-color: #f0c090;
	}

	.meta-chip__label {
		font-size: 0.625rem;
		font-weight: 700;
		text-transform: uppercase;
		letter-spacing: 0.08em;
		color: var(--text-3);
	}

	.meta-chip--accent .meta-chip__label { color: var(--accent-dark); }

	.meta-chip__value {
		font-size: 0.9375rem;
		font-weight: 600;
		color: var(--text);
		line-height: 1.2;
	}

	.meta-chip--accent .meta-chip__value {
		color: var(--accent);
		font-family: var(--font-mono);
	}

	/* ── Collapsible sections ── */
	details { border: none; }

	summary.collapsible {
		cursor: pointer;
		list-style: none;
		display: flex;
		align-items: center;
		gap: 0.5rem;
		user-select: none;
	}

	summary.collapsible::after {
		content: '▾';
		font-size: 0.75rem;
		color: var(--text-3);
		transition: transform 0.15s;
	}

	details:not([open]) summary.collapsible::after {
		transform: rotate(-90deg);
	}

	summary::-webkit-details-marker { display: none; }

	/* ── Note ── */
	.note-content :global(p) {
		font-size: 0.9375rem;
		color: var(--text-2);
		line-height: 1.7;
	}

	.note-content :global(p + p) { margin-top: 0.5rem; }

	/* ── Markdown ── */
	.md-content :global(code) {
		font-family: var(--font-mono);
		font-size: 0.8125rem;
		background: var(--bg-subtle);
		padding: 0.1em 0.35em;
		border-radius: 3px;
	}

	/* ── Stat table ── */
	.stat-table th, .stat-table td { padding: 0.55rem 0.75rem; }

	.seq-cell {
		font-family: var(--font-mono);
		font-size: 0.75rem;
		color: var(--text-3);
		text-align: center;
	}

	.scan-type { font-size: 0.8125rem; color: var(--text-3); }

	.stat-val {
		font-family: var(--font-mono);
		font-size: 0.875rem;
		text-align: right;
	}

	.stat-total {
		font-family: var(--font-mono);
		font-weight: 700;
		font-size: 0.875rem;
		color: var(--accent);
		text-align: right;
	}

	.rank-cell {
		font-family: var(--font-mono);
		font-weight: 700;
		color: var(--accent);
	}
</style>

// src/app/explorers/[slug]/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import {
  getExplorers,
  getExplorerBySlug,
  getOrbById,
  getFullName,
  getLatestRanking,
  formatRank,
  formatDate,
  formatCitation,
  getNationalityFlag,
} from "@/lib/data";
import { CitationBadge } from "@/components/CitationBadge";

export async function generateStaticParams() {
  const explorers = getExplorers();
  return explorers.map((e) => ({ slug: e.slug }));
}

export async function generateMetadata(
  props: PageProps<"/explorers/[slug]">
): Promise<Metadata> {
  const { slug } = await props.params;
  const explorer = getExplorerBySlug(slug);
  if (!explorer) return { title: "Explorer Not Found" };
  const name = getFullName(explorer);
  return {
    title: `${name}${explorer.moniker ? ` "${explorer.moniker}"` : ""}`,
    description: `Stats, rankings, and skill orbs for ${name} from D-Genesis.`,
  };
}

export default async function ExplorerDetailPage(
  props: PageProps<"/explorers/[slug]">
) {
  const { slug } = await props.params;
  const explorer = getExplorerBySlug(slug);
  if (!explorer) notFound();

  const name = getFullName(explorer);
  const latestRanking = getLatestRanking(explorer);
  const flag = getNationalityFlag(explorer.nationality);

  // Sort rankings by date (most recent first)
  const sortedRankings = [...explorer.rankings].sort((a, b) => {
    const dateA = a.date_noted ? new Date(a.date_noted).getTime() : 0;
    const dateB = b.date_noted ? new Date(b.date_noted).getTime() : 0;
    return dateB - dateA;
  });

  // Sort stats by date and sequence
  const sortedStats = [...explorer.stats].sort((a, b) => {
    const dateA = a.date_noted ? new Date(a.date_noted).getTime() : 0;
    const dateB = b.date_noted ? new Date(b.date_noted).getTime() : 0;
    if (dateA !== dateB) return dateA - dateB;
    return (a.date_sequence || 0) - (b.date_sequence || 0);
  });

  return (
    <>
      <div className="detail-header">
        <div className="detail-breadcrumb">
          <Link href="/explorers">← WDARL Rankings</Link>
        </div>
        <h1 className="detail-title">
          {name}
          {!explorer.public && <span className="wdarl-anon-badge">✱ Anonymous on WDARL</span>}
        </h1>
        {explorer.moniker && (
          <div className="detail-subtitle">
            &ldquo;{explorer.moniker}&rdquo;
          </div>
        )}
        <div className="detail-meta">
          <div className="detail-meta-item">
            <span className="detail-meta-label">Rank:</span>
            <strong style={{ color: "var(--accent-amber)", fontFamily: "var(--font-mono)" }}>
              #{formatRank(latestRanking)}
            </strong>
          </div>
          {explorer.sex && (
            <div className="detail-meta-item">
              <span className="detail-meta-label">Sex:</span>
              <span>{explorer.sex}</span>
            </div>
          )}
          {explorer.birthday && (
            <div className="detail-meta-item">
              <span className="detail-meta-label">Birthday:</span>
              <span>{explorer.birthday}</span>
            </div>
          )}
          {explorer.nationality && (
            <div className="detail-meta-item">
              <span className="detail-meta-label">Nationality:</span>
              <span>
                {flag} {explorer.nationality}
              </span>
            </div>
          )}
          {explorer.date_first_known && (
            <div className="detail-meta-item">
              <span className="detail-meta-label">First Known:</span>
              <span>{formatDate(explorer.date_first_known)}</span>
            </div>
          )}
          {latestRanking?.citation && (
            <div className="detail-meta-item">
              <span className="detail-meta-label">Rank Citation:</span>
              <CitationBadge citation={latestRanking.citation} />
            </div>
          )}
        </div>
      </div>

      {explorer.note && (
        <section className="detail-section">
          <h2 className="detail-section-title">Note</h2>
          <div className="card" style={{ padding: 'var(--space-md)', whiteSpace: 'pre-wrap', lineHeight: '1.6' }} dangerouslySetInnerHTML={{ __html: explorer.note }} />
        </section>
      )}

      {/* ── Orbs Used ─────────────────── */}
      <section className="detail-section">
        <h2 className="detail-section-title">Orbs Used</h2>
        {explorer.orbs_used.length > 0 ? (
          <>
            {/* Desktop table */}
            <div className="data-table-wrapper detail-desktop-only">
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Orb Name</th>
                    <th>Date Acquired</th>
                    <th>Note</th>
                    <th>Citation</th>
                  </tr>
                </thead>
                <tbody>
                  {explorer.orbs_used.map((orbUsed, i) => {
                    const orbInfo = orbUsed.orb_id
                      ? getOrbById(orbUsed.orb_id)
                      : null;
                    return (
                      <tr key={i}>
                        <td>
                          {orbInfo ? (
                            <Link
                              href={`/orbs/${orbInfo.slug}`}
                              style={{ color: "var(--accent-teal)" }}
                            >
                              {orbInfo.orb_name}
                            </Link>
                          ) : (
                            <span className="value-muted">Unknown Orb</span>
                          )}
                        </td>
                        <td>{formatDate(orbUsed.date_acquired)}</td>
                        <td style={{ whiteSpace: "normal", maxWidth: "300px" }}>
                          {orbUsed.date_note || "—"}
                        </td>
                        <td>
                          <CitationBadge citation={orbUsed.citation} />
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
              </table>
            </div>
            {/* Mobile stacked cards */}
            <div className="detail-mobile-only">
              {explorer.orbs_used.map((orbUsed, i) => {
                const orbInfo = orbUsed.orb_id
                  ? getOrbById(orbUsed.orb_id)
                  : null;
                return (
                  <div key={i} className="mobile-stacked-card">
                    <div className="mobile-stacked-row mobile-stacked-row-primary">
                      <span className="mobile-stacked-name">
                        {orbInfo ? (
                          <Link
                            href={`/orbs/${orbInfo.slug}`}
                            style={{ color: "var(--accent-teal)" }}
                          >
                            {orbInfo.orb_name}
                          </Link>
                        ) : (
                          <span className="value-muted">Unknown Orb</span>
                        )}
                      </span>
                      <span className="mobile-stacked-date">
                        {formatDate(orbUsed.date_acquired)}
                      </span>
                    </div>
                    {orbUsed.date_note && (
                      <div className="mobile-stacked-row mobile-stacked-row-note">
                        {orbUsed.date_note}
                      </div>
                    )}
                    {orbUsed.citation && (
                      <div className="mobile-stacked-row mobile-stacked-row-citation">
                        <CitationBadge citation={orbUsed.citation} />
                      </div>
                    )}
                  </div>
                );
              })}
            </div>
          </>
        ) : (
          <p style={{ color: "var(--text-muted)" }}>
            No orbs known to have been used.
          </p>
        )}
      </section>

      {/* ── Rankings Over Time ─────────── */}
      <section className="detail-section">
        <h2 className="detail-section-title">Rankings Over Time</h2>
        {sortedRankings.length > 0 ? (
          <>
            {/* Desktop table */}
            <div className="data-table-wrapper detail-desktop-only">
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Rank</th>
                    <th>Known Above</th>
                    <th>Date Noted</th>
                    <th>Citation</th>
                  </tr>
                </thead>
                <tbody>
                  {sortedRankings.map((ranking, i) => (
                    <tr key={i}>
                      <td className="value-highlight">
                        {ranking.rank && ranking.rank !== 0
                          ? ranking.rank.toLocaleString()
                          : "—"}
                      </td>
                      <td>
                        {ranking.known_above_rank
                          ? `Above ${ranking.known_above_rank.toLocaleString()}`
                          : "—"}
                      </td>
                      <td>{formatDate(ranking.date_noted)}</td>
                      <td>
                        <CitationBadge citation={ranking.citation} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            {/* Mobile stacked cards */}
            <div className="detail-mobile-only">
              {sortedRankings.map((ranking, i) => (
                <div key={i} className="mobile-stacked-card">
                  <div className="mobile-stacked-row mobile-stacked-row-primary">
                    <span>
                      <span className="value-highlight" style={{ marginRight: "var(--space-sm)" }}>
                        {ranking.rank && ranking.rank !== 0
                          ? `#${ranking.rank.toLocaleString()}`
                          : "—"}
                      </span>
                      {ranking.known_above_rank && (
                        <span className="value-muted" style={{ fontSize: "0.8rem" }}>
                          Above {ranking.known_above_rank.toLocaleString()}
                        </span>
                      )}
                    </span>
                    <span className="mobile-stacked-date">
                      {formatDate(ranking.date_noted)}
                    </span>
                  </div>
                  {ranking.citation && (
                    <div className="mobile-stacked-row mobile-stacked-row-citation">
                      <CitationBadge citation={ranking.citation} />
                    </div>
                  )}
                </div>
              ))}
            </div>
          </>
        ) : (
          <p style={{ color: "var(--text-muted)" }}>
            No ranking history available.
          </p>
        )}
      </section>

      {/* ── Explorer Stats ─────────────── */}
      <section className="detail-section">
        <h2 className="detail-section-title">Explorer Stats</h2>
        {sortedStats.length > 0 ? (
          <>
            {/* Desktop table */}
            <div className="data-table-wrapper detail-desktop-only">
              <table className="data-table">
                <thead>
                  <tr>
                    <th>Date</th>
                    <th>Seq</th>
                    <th>Scan</th>
                    <th>SP</th>
                    <th>HP</th>
                    <th>MP</th>
                    <th>STR</th>
                    <th>VIT</th>
                    <th>INT</th>
                    <th>AGI</th>
                    <th>DEX</th>
                    <th>LUC</th>
                    <th>Total</th>
                    <th>Dev</th>
                    <th>Citation</th>
                  </tr>
                </thead>
                <tbody>
                  {sortedStats.map((stat, i) => (
                    <tr key={i}>
                      <td>{formatDate(stat.date_noted)}</td>
                      <td className="value-muted">{stat.date_sequence ?? "—"}</td>
                      <td>{stat.scan_type || "—"}</td>
                      <td className="value-highlight">
                        {stat.sp !== null ? stat.sp : "—"}
                      </td>
                      <td>{stat.hp !== null ? stat.hp : "—"}</td>
                      <td>{stat.mp !== null ? stat.mp : "—"}</td>
                      <td>{stat.str ?? "—"}</td>
                      <td>{stat.vit ?? "—"}</td>
                      <td>{stat.int ?? "—"}</td>
                      <td>{stat.agi ?? "—"}</td>
                      <td>{stat.dex ?? "—"}</td>
                      <td>{stat.luc ?? "—"}</td>
                      <td className="value-highlight">
                        {stat.stat_total ?? "—"}
                      </td>
                      <td>{stat.points_from_average ?? "—"}</td>
                      <td>
                        <CitationBadge citation={stat.citation} />
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
            {/* Mobile stat cards */}
            <div className="detail-mobile-only">
              {sortedStats.map((stat, i) => (
                <div key={i} className="mobile-stat-card">
                  <div className="mobile-stat-header">
                    <div className="mobile-stat-header-row">
                      <span>
                        {formatDate(stat.date_noted)}
                        {stat.date_sequence != null && (
                          <span className="value-muted"> · #{stat.date_sequence}</span>
                        )}
                      </span>
                    </div>
                    <div className="mobile-stat-header-row">
                      <span className="value-muted">
                        {stat.scan_type || "—"}
                      </span>
                      <span className="value-highlight">
                        SP {stat.sp !== null ? stat.sp : "—"}
                      </span>
                    </div>
                  </div>
                  <div className="mobile-stat-grid">
                    <div className="mobile-stat-cell">
                      <span className="mobile-stat-label">HP</span>
                      <span className="mobile-stat-value">{stat.hp !== null ? stat.hp : "—"}</span>
                    </div>
                    <div className="mobile-stat-cell">
                      <span className="mobile-stat-label">MP</span>
                      <span className="mobile-stat-value">{stat.mp !== null ? stat.mp : "—"}</span>
                    </div>
                    <div className="mobile-stat-cell">
                      <span className="mobile-stat-label">STR</span>
                      <span className="mobile-stat-value">{stat.str ?? "—"}</span>
                    </div>
                    <div className="mobile-stat-cell">
                      <span className="mobile-stat-label">VIT</span>
                      <span className="mobile-stat-value">{stat.vit ?? "—"}</span>
                    </div>
                    <div className="mobile-stat-cell">
                      <span className="mobile-stat-label">INT</span>
                      <span className="mobile-stat-value">{stat.int ?? "—"}</span>
                    </div>
                    <div className="mobile-stat-cell">
                      <span className="mobile-stat-label">AGI</span>
                      <span className="mobile-stat-value">{stat.agi ?? "—"}</span>
                    </div>
                    <div className="mobile-stat-cell">
                      <span className="mobile-stat-label">DEX</span>
                      <span className="mobile-stat-value">{stat.dex ?? "—"}</span>
                    </div>
                    <div className="mobile-stat-cell">
                      <span className="mobile-stat-label">LUC</span>
                      <span className="mobile-stat-value">{stat.luc ?? "—"}</span>
                    </div>
                  </div>
                  <div className="mobile-stat-totals">
                    <span>
                      <span className="mobile-stat-label">Total</span>
                      <span className="value-highlight">{stat.stat_total ?? "—"}</span>
                    </span>
                    <span>
                      <span className="mobile-stat-label">Dev</span>
                      <span>{stat.points_from_average ?? "—"}</span>
                    </span>
                  </div>
                  {stat.citation && (
                    <div className="mobile-stacked-row mobile-stacked-row-citation">
                      <CitationBadge citation={stat.citation} />
                    </div>
                  )}
                </div>
              ))}
            </div>
          </>
        ) : (
          <p style={{ color: "var(--text-muted)" }}>No stats available.</p>
        )}
      </section>

      {/* ── Radar Chart Placeholder ────── */}
      {sortedStats.length > 0 && (
        <section className="detail-section">
          <h2 className="detail-section-title">Stat Visualization</h2>
          <div className="radar-placeholder">
            <div className="radar-placeholder-icon">📊</div>
            <p>Radar / Spider chart coming soon</p>
            <p style={{ fontSize: "0.8rem", marginTop: "0.5rem" }}>
              Will visualize STR, VIT, INT, AGI, DEX, LUC over time
            </p>
          </div>
        </section>
      )}
    </>
  );
}
