// web/src/routes/orbs/[slug]/+page.svelte
<script lang="ts">
	import type { PageData } from './$types';
	import { getFullName, formatProbability, formatCooldown, formatCitation } from '$lib/utils';
	let { data }: { data: PageData } = $props();
	const orb = $derived(data.orb);

	function formatEffects(html: string | null): string[] {
		if (!html) return [];
		return html.split(/<br\s*\/?>/gi).map(s => s.trim()).filter(Boolean);
	}
</script>

<svelte:head><title>{orb.orb_name} — D-Genesis Info</title></svelte:head>

<div class="container page">
	<a href="/orbs" class="back-link">← Skill Orbs</a>

	<div class="orb-header">
		<h1 class="page-title">{orb.orb_name}</h1>
		<span class="badge badge--id">Orb #{orb.orb_id}</span>
	</div>

	{#if orb.known_effects}
		<div class="data-section">
			<p class="section-heading">Known Effects</p>
			<div class="card">
				{#each formatEffects(orb.known_effects) as line}
					<p class="rich-text">{@html line}</p>
				{/each}
			</div>
		</div>
	{/if}

	{#if orb.note}
		<div class="data-section">
			<p class="section-heading">Notes</p>
			<div class="card note-card">
				{#each formatEffects(orb.note) as line}
					<p class="rich-text">{@html line}</p>
				{/each}
			</div>
		</div>
	{/if}

	{#if orb.drop_rates.length}
		<div class="data-section">
			<p class="section-heading">Drop Rates</p>
			<div class="card" style="padding: 0; overflow: hidden;">
				<table class="data-table">
					<thead>
						<tr>
							<th>Dropped By</th>
							<th>Dungeon</th>
							<th>Floor</th>
							<th>Probability</th>
							<th>Making Cooldown</th>
							<th>Citation</th>
						</tr>
					</thead>
					<tbody>
						{#each orb.drop_rates as dr}
							<tr>
								<td>{dr.creature ?? '—'}</td>
								<td>{dr.dungeon ?? '—'}</td>
								<td>{#if dr.floor}{@html dr.floor}{:else}—{/if}</td>
								<td>
									{#if dr.favorable_outcomes && dr.total_events}
										<span class="accent-num">{formatProbability(dr.favorable_outcomes, dr.total_events)}</span>
									{:else}
										<span style="color: var(--text-3)">—</span>
									{/if}
								</td>
								<td>{formatCooldown(dr.total_events) || '—'}</td>
								<td>
									{#if dr.citation.volume}
										<span class="badge badge--citation">{formatCitation(dr.citation)}</span>
									{:else}
										<span style="color: var(--text-3)">—</span>
									{/if}
								</td>
							</tr>
						{/each}
					</tbody>
				</table>
			</div>
		</div>
	{/if}

	{#if data.users.length}
		<div class="data-section">
			<p class="section-heading">Known Users</p>
			<div class="users-grid">
				{#each data.users as c}
					<a href="/characters/{c.slug}" class="user-chip">
						{getFullName(c)}
					</a>
				{/each}
			</div>
		</div>
	{/if}
</div>

<style>
	.orb-header {
		display: flex;
		align-items: baseline;
		gap: 0.75rem;
		margin-bottom: 0.25rem;
		flex-wrap: wrap;
	}

	.note-card {
		border-left: 3px solid var(--accent);
	}

	.note-card .rich-text + .rich-text {
		margin-top: 0.5rem;
	}

	.card .rich-text + .rich-text {
		margin-top: 0.5rem;
	}

	.users-grid {
		display: flex;
		flex-wrap: wrap;
		gap: 0.5rem;
	}

	.user-chip {
		display: inline-flex;
		align-items: center;
		padding: 0.375rem 0.75rem;
		background: var(--bg-card);
		border: 1px solid var(--border);
		border-radius: 999px;
		font-size: 0.875rem;
		color: var(--text);
		text-decoration: none;
		transition: border-color 0.15s, color 0.15s;
	}

	.user-chip:hover {
		border-color: var(--accent);
		color: var(--accent);
		text-decoration: none;
	}
</style>

// src/app/orbs/[slug]/page.tsx
import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import {
  getOrbs,
  getOrbBySlug,
  formatDate,
  formatProbability,
  formatCooldown,
} from "@/lib/data";
import { CitationBadge } from "@/components/CitationBadge";

export async function generateStaticParams() {
  const orbs = getOrbs();
  return orbs.map((o) => ({ slug: o.slug }));
}

export async function generateMetadata(
  props: PageProps<"/orbs/[slug]">
): Promise<Metadata> {
  const { slug } = await props.params;
  const orb = getOrbBySlug(slug);
  if (!orb) return { title: "Orb Not Found" };
  return {
    title: `${orb.orb_name}`,
    description: `Drop rates and effects for the ${orb.orb_name} skill orb from D-Genesis.`,
  };
}

export default async function OrbDetailPage(
  props: PageProps<"/orbs/[slug]">
) {
  const { slug } = await props.params;
  const orb = getOrbBySlug(slug);
  if (!orb) notFound();

  // Strip HTML for text display, but allow it in dangerouslySetInnerHTML
  const effectsPlainText = orb.known_effects
    ? orb.known_effects.replace(/<[^>]*>/g, " ").trim()
    : null;

  return (
    <>
      <div className="detail-header">
        <div className="detail-breadcrumb">
          <Link href="/orbs">← Skill Orbs</Link>
        </div>
        <h1 className="detail-title">{orb.orb_name || "Unknown Orb"}</h1>
      </div>

      {/* ── Effects ───────────────────── */}
      <section className="detail-section">
        <h2 className="detail-section-title">Known Effects</h2>
        <div
          className="contribute-card"
          style={{ borderLeft: "3px solid var(--accent-teal)" }}
        >
          {orb.known_effects ? (
            <p
              style={{ color: "var(--text-primary)", lineHeight: 1.8 }}
              dangerouslySetInnerHTML={{
                __html: orb.known_effects.replace(/<br\s*\/?>/g, "<br />"),
              }}
            />
          ) : (
            <p style={{ color: "var(--text-muted)", fontStyle: "italic" }}>
              Not documented
            </p>
          )}
        </div>
      </section>

      {/* ── Note ──────────────────────── */}
      {orb.note && (
        <section className="detail-section">
          <h2 className="detail-section-title">Note</h2>
          <div
            className="contribute-card"
            style={{ borderLeft: "3px solid var(--accent-purple)" }}
          >
            <p style={{ color: "var(--text-secondary)", fontStyle: "italic" }}>
              {orb.note}
            </p>
          </div>
        </section>
      )}

      {/* ── Drop Rates ────────────────── */}
      <section className="detail-section">
        <h2 className="detail-section-title">Drop Rates</h2>
        {orb.drop_rates.length > 0 ? (
          <div className="data-table-wrapper">
            <table className="data-table">
              <thead>
                <tr>
                  <th>Dropped By</th>
                  <th>In Dungeon</th>
                  <th>On Floor</th>
                  <th>Probability</th>
                  <th>Cooldown</th>
                  <th>Citation</th>
                </tr>
              </thead>
              <tbody>
                {orb.drop_rates.map((rate, i) => (
                  <tr key={i}>
                    <td style={{ color: "var(--accent-teal)" }}>
                      {rate.creature || "Unknown"}
                    </td>
                    <td>{rate.dungeon || "Unknown"}</td>
                    <td>
                      {rate.floor ? (
                        <span
                          dangerouslySetInnerHTML={{ __html: rate.floor }}
                        />
                      ) : (
                        "Unknown"
                      )}
                    </td>
                    <td className="value-highlight">
                      {formatProbability(
                        rate.favorable_outcomes,
                        rate.total_events
                      )}
                    </td>
                    <td>
                      {rate.favorable_outcomes && rate.total_events
                        ? formatCooldown(rate.total_events)
                        : "—"}
                    </td>
                    <td>
                      <CitationBadge citation={rate.citation} />
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        ) : (
          <p style={{ color: "var(--text-muted)" }}>No known drop rates.</p>
        )}
      </section>
    </>
  );
}
